'@startuml
'
'class Main {
'  - geopandas: Module
'  - pandas: Module
'  - streamlit: Module
'  - plotlyExpress: Module
'  - graphObjs: Module (from plotly)
'  - ARIMA: Class (from statsmodels)
'  - Point: Class (from shapely)
'  - data: DataFrame
'  - page: String
'  - selected_country: String
'  + predictCrimeRate()
'}
'
'class Prediction {
'  - pandas: Module
'  - adfuller: Function (from statsmodels.tsa.stattools)
'  - ARIMA: Class (from statsmodels)
'  + predictCrimeRate(): Function
'}
'
'Main --> Prediction: predictCrimeRate()
'
@enduml
